### ISSUE TITLE
درس ۱ راست‌‌چین نشده

### ISSUE THREAD

**Issue by ohmydevops** [sajadadineh/rabbitmq-persian#2]
الان متوجه شدم یادم رفته درس ۱ رو راست چین کنم :) زحمتت @sajadadineh

**Comment by sajadadineh** [comment]
فدای سرت 
قراره این داک کم کم کامل بشه منم هنوز بقیشو ننوشتم 
ممنونم ازت

**Comment by ohmydevops** [comment]
هماهنگه
